# Generated by Django 3.0 on 2019-12-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_address_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
