# Generated by Django 3.0 on 2019-12-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
