# Generated by Django 3.0 on 2019-12-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
